"""empty message

Revision ID: 4aa485759e1f
Revises: 84838024e185
Create Date: 2019-04-15 13:24:22.210580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aa485759e1f'
down_revision = '84838024e185'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proforma', sa.Column('sales_commission_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proforma', 'sales_commission_rate')
    # ### end Alembic commands ###
