"""empty message

Revision ID: 74c881fa270b
Revises: e2c438be9199
Create Date: 2019-01-03 12:27:09.977611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74c881fa270b'
down_revision = 'e2c438be9199'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('loan', sa.Column('proforma_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'loan', 'proforma', ['proforma_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'loan', type_='foreignkey')
    op.drop_column('loan', 'proforma_id')
    # ### end Alembic commands ###
