"""empty message

Revision ID: 84838024e185
Revises: e75446c22b87
Create Date: 2019-04-15 11:57:19.369487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84838024e185'
down_revision = 'e75446c22b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proforma', sa.Column('property_appreciation_rate', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proforma', 'property_appreciation_rate')
    # ### end Alembic commands ###
