"""empty message

Revision ID: 88433cb87fa8
Revises: afe0a1996296
Create Date: 2019-04-20 12:02:00.489127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88433cb87fa8'
down_revision = 'afe0a1996296'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('property_tax', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'property_tax')
    # ### end Alembic commands ###
