"""empty message

Revision ID: 9b5b9e024507
Revises: 88433cb87fa8
Create Date: 2019-04-20 13:11:51.361317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b5b9e024507'
down_revision = '88433cb87fa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_item', sa.Column('amount_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_item', 'amount_type')
    # ### end Alembic commands ###
