"""empty message

Revision ID: afe0a1996296
Revises: 4aa485759e1f
Create Date: 2019-04-20 11:45:49.987241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe0a1996296'
down_revision = '4aa485759e1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('proforma', sa.Column('description', sa.String(length=5000), nullable=True))
    op.add_column('proforma', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proforma', 'title')
    op.drop_column('proforma', 'description')
    # ### end Alembic commands ###
