"""empty message

Revision ID: e3d86d08d3e1
Revises: c344e0f9cde4
Create Date: 2019-01-02 17:09:57.065945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3d86d08d3e1'
down_revision = 'c344e0f9cde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proforma',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=True),
    sa.Column('arv', sa.Integer(), nullable=True),
    sa.Column('purchase_price', sa.Integer(), nullable=True),
    sa.Column('seller_concessions', sa.Integer(), nullable=True),
    sa.Column('closing_costs', sa.Integer(), nullable=True),
    sa.Column('rent_ready_costs', sa.Integer(), nullable=True),
    sa.Column('initial_reserve_amount', sa.Integer(), nullable=True),
    sa.Column('lease_option_fee', sa.Integer(), nullable=True),
    sa.Column('total_finished_sq_foot', sa.Integer(), nullable=True),
    sa.Column('land_value_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('income_tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('vacancy_perc', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name='fk_Proforma_created_by_id', use_alter=True),
    sa.ForeignKeyConstraint(['property_id'], ['property.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['user.id'], name='fk_Proforma_updated_by_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proforma')
    # ### end Alembic commands ###
