"""empty message

Revision ID: f2453c8b2474
Revises: 9b5b9e024507
Create Date: 2019-04-20 13:13:29.593379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2453c8b2474'
down_revision = '9b5b9e024507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('line_item', sa.Column('calculation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('line_item', 'calculation')
    # ### end Alembic commands ###
